version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"       # MQTT 기본 포트
      - "9001:9001"       # MQTT over WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config

  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mqtt
    volumes:
      - ./uploads:/app/uploads
